# Generated by Django 5.0.3 on 2024-03-23 07:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Fasad', 'Fasad'), ('Tiokliya', 'Tiokliya'), ('Qoliplik', 'Qoliplik')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='basket',
            name='address',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='subject',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='Telefon raqam xato', message="Telefon raqamingizni to'g'ri ko'rsating.", regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('country', models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Rusian', 'Rusian'), ('English', 'English')], max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='dashboard.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(to='dashboard.products'),
        ),
    ]
