# Generated by Django 5.0.3 on 2024-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_basket_product_alter_checkout_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
