# Generated by Django 5.0.3 on 2024-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_products_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.TextField(),
        ),
    ]
