# Generated by Django 4.2.4 on 2024-03-22 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_contact_image_remove_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=1, max_length=17, validators=[django.core.validators.RegexValidator(code='Telefon raqam xato', message="Telefon raqamingizni to'g'ri ko'rsating.", regex='^[\\+]9{2}8{1}[0-9]{9}$')]),
            preserve_default=False,
        ),
    ]
