# Generated by Django 4.2.4 on 2024-03-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_image_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
