# Generated by Django 5.0.3 on 2024-03-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='message',
        ),
    ]
