# Generated by Django 5.0.2 on 2024-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About1',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(),
        ),
    ]
