# Generated by Django 5.0.3 on 2024-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
